#ENC[AES256_GCM,data:voPEOBC+VmVQoNF61mVtA2nTV4amKMCSSxNs1HWuoZf8gAKzOJM3fQneXnKaiISMhFo+essT7aMsnh5hp5UcD2aVTB8IVD2ixooS/ItL+939UEWRgeR+cXqU4wsZTFc=,iv:MrOHjpqQ8yUEoML2xLkEF7vlRHerJ6CMCsKZlbjXof0=,tag:9jjM7DaW9HuL5fJyg3NTXg==,type:comment]
crowdsec_bouncer_key: ENC[AES256_GCM,data:bKfjsa4MDwZ3jC4BS70aA0/SAYtE1G3s4urDdzGfHGbkyy1QZhm6CUDTTY7zQFmEsNYa1jEBSuYtDzeqWDB13A==,iv:gRuc+dc9bz+EsBTHdrGHcN4QRs4VF11wNJDxtbzoA1o=,tag:rTfPJPImoH1SoDXMCPHezA==,type:str]
crowdsec_enroll_key: ENC[AES256_GCM,data:frS00jGFtqjLUP+aFU9BRb/t,iv:gw6ju2/SD/DwU2y6Zbm3/7YaSPY8TQwXLFX42e6Rytg=,tag:xiMv/WCYL+7XmXkqyhVxSA==,type:str]
auth_secret: ENC[AES256_GCM,data:nLk2evqXEzHZSHp32Cdbzkq1kTcECBTtjdXCn7R2juctp7kU55ssIvyKFR+1lBLz,iv:50WTxp9aaTGsnAroQCdB41IUg7HKbC4F1gxLreX5bpU=,tag:qKREAdg5DGsfpHzd7Kl2rg==,type:str]
web_bff_client_secret: ENC[AES256_GCM,data:HpsYnGNPChH59uk9FPS6VvgdmV/g7thjQgpOk28X9HtCR5KgyoDN+DJD9swc5953,iv:EMRyA2GEk5mg0lRfwzHok+ejaCOX8zkdy74DrSFOgYM=,tag:2sGaAWpSc784OZ1JVesQIA==,type:str]
portainer_agent_secret: ENC[AES256_GCM,data:vu1Kklc3fYNEhBJpS/zNTi0btK+WGyUX4PtJFznNZEbyNje2cq8vzqj4gpu4Ttff,iv:wD3j5vLeLCkDVulNLQ9G2zsJp7kioWP7xJSYKEEUY60=,tag:5DLKnAmsidnfKRS97ECbnQ==,type:str]
wireguard_psk_core: ENC[AES256_GCM,data:OXg+bRsmuR5Rm0pberLozwfYE89NcETg1ERyi948eI2GzAfs6vUYnX6yo/E=,iv:E3OdglE+9zkdhvupsLEfsCVKJHw66lNITJ6A7U8JLUU=,tag:HRAy3egsYqfeOzj8CsYFXw==,type:str]
wireguard_psk_owner-laptop: ENC[AES256_GCM,data:Kl0XXZmMVNQUC+6g/tIqbgVYPccWS9A5khw/Np+HuAChwVggJ7gBgcNfOWM=,iv:TCr2Cnc0IiGv2/+016NFWkEKvHXZmyIO9bku9yt3Qq0=,tag:Lyy/erpQRP0ci0R1WJYY+w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxYVd1eWd2am5lY2txNVJU
            Vy9WaDVDQzJTczVEbjhIOENudUdnRldWSG1rClR4RVVVTWFSQWJrcFR0UUxYTkJG
            ZUtxUGJrRzR5N01WYmxWQzNCK1duT2sKLS0tIHVnRW93UGhnYm9zZ3I4Y0tUM3h4
            MHJmRmNLYUhuUlZSM0J1NFBITkVCQ0EKcvyZfqFf2qG/sF9HWtveSJMn3PAPhHJp
            xJ05iZ8sAqPCyHH3RzwaRyd7oQ2J+joiM6W0DOvjOa8P6kmQu/AYTg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1c87ztw79n3sk6s0a7j42z8cahe7wqvgaytme3kg6t7827meezsyqv8skmd
    lastmodified: "2026-09-17T02:52:31Z"
    mac: ENC[AES256_GCM,data:8gCJuFW4yvMeaOC829mvq2jq+k19HNEQUrf7kxSwvqQ4vke3dTfap0QqZW0EF0yPipvNsIeyWzAjM/dL5J+w0Be0jW7qEFb+R4BnxysLpQj95amoiwK86I/G4Q0WaVSUnE2tMs8ttuAu/XhRPCJsnAW4d1ubcKEcZEl1X19RmXw=,iv:ejg2h9xPrG0Se85pmki+9Hv/5RqfjVwNv8iBuawAntQ=,tag:QtyPpOurOi96Cq/8j1Xy9w==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
